export enum ProjectType {
  WOO_COMMERCE = 'WooCommerce',
  SHOPIFY = 'Shopify',
  MAGENTO = 'Magento',
  PRESTASHOP = 'PrestaShop',
  BIG_COMMERCE = 'BigCommerce',
  OPENCART = 'OpenCart',
  SQUARESPACE = 'Squarespace',
  WIX_ECOMMERCE = 'Wix eCommerce',
  ECWID = 'Ecwid',
  WORDPRESS = 'WordPress',
  JOOMLA = 'Joomla',
  DRUPAL = 'Drupal',
  CUSTOM_WEBSITE = 'Custom Website',
  MOBILE_APP = 'Mobile App',
  WEB_APPLICATION = 'Web Application',
  LANDING_PAGE = 'Landing Page',
  BLOG_SITE = 'Blog Site',
  PORTFOLIO_SITE = 'Portfolio Site',
  ELEARNING_PLATFORM = 'E-Learning Platform',
  SOCIAL_NETWORK = 'Social Network',
  MARKETPLACE_PLATFORM = 'Marketplace Platform',
  SAAS_PLATFORM = 'SaaS Platform',
  OTHER = 'Other',
}
